# Use an appropriate base image
FROM ubuntu:latest

# Specify the volume
VOLUME /data

# Add other instructions (if any)
# For example, you might want to add a default command
CMD ["sleep", "infinity"]
